import tweepy

BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAALlJbwEAAAAAFGyARZFxHda2jKtA2Xo89mKgbNY%3DG5bFQ1ETRCDuuaw3ZBjVRI5rN7s0eCAFTtV0bciszUzox8KTSl"
API_KEY = "SLorzFHwN67VXfRuCgshWuWqA"
API_KEY_SECRET = "6n98mGBPFIp5J51xUEetFiBL6hznpBSEPoGLhrF30Gkf2pf1eO"
ACCESS_TOKEN = "188690550-M8glP7JlMW6G9x53mjwOf6N1iUvIYPylzAIVyBxC"
ACCESS_TOKEN_SECRET = "Y10Gb2fZecGZSBoGvISwGf6gQ4q7WDxroNA6nRVrOEKJn"
auth = tweepy.OAuth1UserHandler(
   API_KEY, API_KEY_SECRET,ACCESS_TOKEN,ACCESS_TOKEN_SECRET)

api = tweepy.API(auth)

public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)